apiVersion: v1
kind: Service
metadata:
  name: kx-docs-service
  namespace: devops
  labels:
    app: kx-docs
spec:
  type: ClusterIP
  ports:
   - port: 80
     targetPort: 80
     protocol: TCP
  selector:
    app: kx-docs
